### PR TITLE
Update layout of results, change German to english.

### PR DESCRIPTION
**Pull request by taebox**
2015-02-10 12_54_15-test html - comodo dragon
Changed some of the old table properties to CSS style. Added some color cues to the table and changed the layout so that horizontal space can be saved. Also changed verbiage of "Command" to "Test steps" the word Summen to Total.

### CODE REVIEW

**Comment by taebox** [comment]
Seeing a missing class error in the build. This is not due to my changes and I do not know how to reconcile this as it doesn't appear the pom file in this repository has any dependencies at all.

java.lang.NoClassDefFoundError: com/sun/mirror/apt/AnnotationProcessorFactory

**Comment by daniel-beck** [comment]
This build failure is caused by the parent POM version specified here:
https://github.com/jenkinsci/seleniumhtmlreport/blob/master/pom.xml#L6

This needs to be at least 1.424 or so for the compile by the PR builder (or JDK 7 in general) to succeed.

Related:
https://wiki.jenkins-ci.org/display/JENKINS/Choosing+Jenkins+version+to+build+against

**Comment by taebox** [comment]
I am currently testing and looking at additional changes for this commit.

**Comment by taebox** [comment]
This is ready to be merged.

**Pull request closed without merging**
